apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        kind: test
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://golang:1.20
        name: Build Go app
        kind: build
        labels: maintainer=compliance,email=engineering@cloudbees.io
        run: |
          go build -v ./...
      - uses: docker://golang:1.20
        name: Run tests
        kind: test
        run: |
          go test -v ./...
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Scan with SonarQube bundled
        kind: scan
